config/routes.rb
Wiki::Application.routes.draw do

  get "comments/new"

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root :to =>  "static_pages#home"
  resources :articles do
    resources :comments
    resources :audits
  end
  resources :users
  resources :categories

  post 'article/preview' => 'articles#preview'
  put 'article/preview' => 'articles#preview'

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  summary     :text
#  content     :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#

class Article < ActiveRecord::Base
  attr_accessible :content, :summary, :title, :tag_list, :category_id
  validates :title, presence: true
  validates :summary, presence: true
  validates :content, presence: true
  validates :user_id, presence: true

  belongs_to :user
  belongs_to :category
  has_many :comments, as: :commentable

  acts_as_taggable

  default_scope order: 'articles.created_at DESC'

  audited except: :tag_list

  def logs(last_log = nil)
    audits = self.audits.updates.descending.includes(:user)
    last_log.nil? ? audits : audits.where("audits.id != ?", last_log.id)
  end

  def self.search(params = {})
    if params[:tag].present?
      Article.tagged_with(params[:tag])
    elsif params[:category_id].present?
      Article.where("articles.category_id = ?", params[:category_id])
    else
      Article.all
    end
  end

  def to_param
    "#{id}-#{title}".parameterize
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5).search(params)
  end
  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(params[:article])
    users = User.all
    if @article.save
      users.each do |u|
        UpdatesMailer.new_article(u, @article).deliver
      end
      redirect_to @article, flash: { notice: t("articles.new.messages.success.saved")}
    else
      render "new"
    end
  end

  def edit
    @article = Article.find(params[:id])
  end
  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to @article, flash: { notice: t("articles.edit.messages.success.saved")}
    else
      render 'edit'
    end
  end
  def show
    @article = Article.find(params[:id])
    @tags = @article.tags.pluck(:name)
    @commentable = @article
    @comments = @commentable.comments.includes(:user).paginate(page: params[:page], per_page: 5)
    @comment = Comment.new
    @last_log = @article.logs.first
    @logs = @article.logs @last_log
    @category = @article.category
  end

  def preview
    @article = current_user.articles.build(params[:article])
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.haml
.link-item
  = image_tag article.user.gravatar_url, class: 'user-avatar'
  = link_to article do
    %h2= article.title
  %span.info Creado el 31 de enero del 2012 por:
  = link_to article.user.username, 'javascript:void(0)', class: 'username'
  %span.summary= article.summary
  .tags
    - article.tags.pluck(:name).each do |tag_name|
      %span.tag= link_to tag_name, articles_path(tag: tag_name)

app/views/articles/_form.html.haml
= form_for(@article, html: {id: 'js-article-form'}) do |f|
  .header-content
    = f.text_field :title, class: 'article-title', :placeholder => "Título"
  .info-article
    .summary
      %span.leasson Agrega una pequeña descripcion de tu articulo:
      = f.text_field :summary, class: 'leassons', :placeholder => "¿Qué aprendiste o aprenderas a leer este articulo?"
      = f.text_field :tag_list, class: "tags-form"
    .category
      = f.label :category_id, t("articles.new.form.category")
      = f.collection_select :category_id, Category.all, :id, :name, prompt: t("articles.new.form.prompt")
  .article-content
    = f.text_area :content
  .instructions
    %span Recuerda que puedes utilizar Markdown para estilizar el conenido.
    %br/ 
    %span.feature
      %b Negritas:
      *example*
    %span.feature
      %b Título
      *example*
    %span.feature
      %b Negritas:
      *example*
    %span.feature
      %b Título
      *example*
  .buttons
    = f.submit t("articles.new.form.submit"), :class => "btn recomendar"
    =link_to "Preview", "javascript:void(0)", id: "js-preview", class: "btn preview"

app/views/articles/_preview_article.html.haml
.article-container
  .header-content
    = image_tag article.user.gravatar_url, class: 'user-avatar'
    %h2.article-title= article.title
    %span.date 
      Creado el 
      = l article.created_at ? article.created_at : Time.now
      por
    %span.username= article.user.username 
  .info-article
    %span.leasson Leassons learned
    %p= find_and_preserve markdown article.summary 
    .tags
      - article.tag_list.each do |t|
        %span.tag= t
  .article-content
    %p= find_and_preserve markdown article.content
  .buttons
    =link_to "Regresar", "javascript:void(0)", id:"js-back", class:"btn recomendar"

app/views/articles/edit.html.haml
- set_meta_tags :description => 'Edición de articulos de conocimiento sobre software publicados por el equipo de IcaliaLabs en Monterrey'
- set_meta_tags :title => 'Edita el articulo'
.write.unit
	.write-container
		.article-container
			= render 'form'
	.prev-container
		

app/views/articles/index.html.haml
- set_meta_tags :description => 'Articulos de conocimiento sobre software publicados por el equipo de IcaliaLabs en Monterrey'
- set_meta_tags :title => 'Lista de articulos'
%section.links
  -if params[:category_id].present?
    %h2.tag-category=Category.find(params[:category_id]).name
  -elsif params[:tag].present?
    %h2.tag-tag=params[:tag]

  .unit#js-articles
    =render @articles
  =will_paginate @articles, page_links: false, previous_label: "", next_label: "Mostrar más", id:"js-articles-pagination"

app/views/articles/index.js.erb
$('#js-articles').append('<%= j render @articles %>');
<% if @articles.next_page %>
  $('#js-articles-pagination').replaceWith('<%= j will_paginate @articles, page_links: false, previous_label: "", next_label: "Mostrar más", id:"js-articles-pagination" %>');
<% else %>
  $('#js-articles-pagination').remove();
<% end %>

app/views/articles/new.html.haml
- set_meta_tags :description => 'Creación de articulos de conocimiento sobre software publicados por el equipo de IcaliaLabs en Monterrey'
- set_meta_tags :title => 'Escribe un articulo'
.write.unit
	.write-container
		.article-container
			= render 'form'
	.prev-container
		

app/views/articles/preview.js.erb
<%= render partial: 'preview_article', locals: { article: @article } %>

app/views/articles/show.html.haml
- set_meta_tags :description => @article.summary
- set_meta_tags :title => @article.title
- set_meta_tags "og:title" => @article.title
- set_meta_tags "og:type" => "article"
- set_meta_tags "og:description" => @article.summary
- set_meta_tags "fb:admins" => "632145692"
- set_meta_tags "twitter:card" => "summary"
- set_meta_tags "twitter:url" => request.url
- set_meta_tags "twitter:title" => @article.title
- set_meta_tags "twitter:description" => @article.summary

.article-container
  .header-content
    = image_tag @article.user.gravatar_url, class: 'user-avatar'
    %h2.article-title= @article.title
    %span.date 
      Creado el 
      = l @article.created_at
      por
    %span.username= @article.user.username
  .info-article
    %span.leasson Leassons learned
    %p= find_and_preserve markdown @article.summary
    .tags
      - @tags.each do |tag_name|
        %span.tag=link_to tag_name, articles_path(tag: tag_name)
  .article-content
    %p= find_and_preserve markdown @article.content
  .feed
    -if @last_log
      %span 
        =link_to "Ultima modificación", article_audit_path(@last_log)
        el
        = l @last_log.created_at
        por
        = @last_log.user.username
    -@logs.each do |l|
      %span
        =link_to "Modificado", article_audit_path(l)
        el
        =l l.created_at
        por
        =l.user.username
  .buttons
    =link_to "Editar", edit_article_path(@article), class: 'edit'
#js-comments.coments-container
  %h3
    =@article.comments.count
    Comments
  -unless current_user
    =link_to "New Comment", new_user_session_path
  -else
    =link_to "New Comment", [:new, @commentable, :comment], id: "js-new-comment-link", remote: true
  =render @comments, article: @article
=will_paginate @comments, page_links: false, previous_label: "", next_label: "Mostrar más", id:"js-comments-pagination"

app/views/articles/show.js.erb
$('#js-comments').append('<%= j render(@comments, article: @article) %>');
<% if @comments.next_page %>
  $('#js-comments-pagination').replaceWith('<%= j will_paginate @comments, page_links: false, previous_label: "", next_label: "Mostrar más", id:"js-comments-pagination" %>');
<% else %>
  $('#js-comments-pagination').remove();
<% end %>