config/routes.rb
Wiki::Application.routes.draw do

  get "comments/new"

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root :to =>  "static_pages#home"
  resources :articles do
    resources :comments
    resources :audits
  end
  resources :users
  resources :categories

  post 'article/preview' => 'articles#preview'
  put 'article/preview' => 'articles#preview'

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :articles

  attr_accessible :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :is_admin?

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to categories_path, flash: { notice: "Category successfully created" }
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to categories_path, flash: { notice: "Category successfully modified" }
    else
      render 'edit'
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    redirect_to categories_path, flash: { notice: "Category successfully deleted" }
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for(@category) do |f|
  .header-content
    = f.text_field :name, class: 'article-title', :placeholder => "Category name"
  .buttons
    = f.submit t("articles.new.form.submit"), :class => "btn recomendar"

app/views/categories/edit.html.haml
=render "form"

app/views/categories/index.html.haml
- @categories.each do |category|
  .link-item
    %span.info
      = category.name
    %span
      = link_to "Edit", edit_category_path(category)
      |
      = link_to "Delete", category, method: :delete,
                                  data: { confirm: "You sure?" }

app/views/categories/new.html.haml
=render "form"