config/routes.rb
Wiki::Application.routes.draw do

  get "comments/new"

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root :to =>  "static_pages#home"
  resources :articles do
    resources :comments
    resources :audits
  end
  resources :users
  resources :categories

  post 'article/preview' => 'articles#preview'
  put 'article/preview' => 'articles#preview'

end

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-32608013-2', 'icalialabs.com');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.haml
- set_meta_tags "og:image" => image_with_host("full_logo.png")
- set_meta_tags "twitter:image" => image_with_host("full_logo.png")
- set_meta_tags "og:url" => request.url

!!!
%html
  %head
    = display_meta_tags :site => 'Wiki de IcaliaLabs'
    %meta{:charset => "utf-8"}
    %meta{:author => 'http://www.icalialabs.com'}
    = stylesheet_link_tag    "application", "http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css", :media => "all"
    = javascript_include_tag "application", "http://code.jquery.com/ui/1.10.3/jquery-ui.js"
    = favicon_link_tag
    = csrf_meta_tags

  %body
    .header
      .container.center
        = link_to root_path, class: 'logo' do
          = image_tag 'logo.png'
        %nav.header-menu
          - if user_signed_in?
            %span.welcome Logged in as
            %strong= current_user.username
            - if user_is_admin?
              = link_to "Admin tools", "javascript:void(0)", class: 'logout'
            = link_to t("users.session.button.logout"), destroy_user_session_path, method: :delete, class: 'logout'
          - else
            = link_to t("users.session.button.login"), new_user_session_path
          .search-box
            = form_tag articles_path, method: :get do
              = text_field_tag :tag, params[:tag], placeholder: "Buqueda por tags", data: { tags: ActsAsTaggableOn::Tag.pluck(:name) }, class: 'search'
              = submit_tag '', class:'icon', value: ''
      .alerts
        -flash.each do |key, msg|
          = content_tag :p, msg, :class => key
    %section.page.container.center
      .col-1
        %nav.side-menu
          %span.title Temas
          - Category.all.each do |category|
            = link_to category.name, articles_path(category_id: category.id)
          = link_to "Escribir Artículo", new_article_path, class: 'actionbutton'
      .col-2
        .unit
          = yield

    = render 'layouts/google_analytics'